### ISSUE TITLE
Don't use JAVA_HOME for JRE detection

### ISSUE THREAD

**Issue by HitkoDev** [google/closure-compiler-npm#105]
`JAVA_HOME` environment variable is supposed to point to the JDK installation (see https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars001.html), however in most cases only JRE will be installed and no `JAVA_HOME` variable will be set. Therefore, it shouldn't be used to determine which implementation of closure compiler to use in https://github.com/google/closure-compiler-npm/blob/3e23bd6450a927ed56f8002de5cb1d293b2a8b3a/lib/utils.js#L24

**Comment by HitkoDev** [comment]
Perhaps use https://www.npmjs.com/package/which, it's about 50% faster than native Linux command (a little bench I did to testo it: https://drone.htk.io/HitkoDev/bench-npm-which/4/3)

**Comment by ChadKillingsworth** [comment]
Is there a reason you can't specify the platform flag?

The auto detection was known to be imperfect, but a sizable portion of users would prefer to default to JavaScript.

**Comment by HitkoDev** [comment]
The problem with JavaScript implementation is that it is slower and uses
significantly more RAM than other versions, which makes it unsuitable for
compiling larger scripts.

>
Imo it's better to remove auto detection altogether and tell users to
specify implementation they want to use, than to have it implemented in a
highly inaccurate way, where users effectively still have to manually
specify the implementation to use.

**Comment by ChadKillingsworth** [comment]
For many systems the auto detection works very well. It isn't perfect, but it wasn't designed to be. There are cases where the java version is faster than the native binaries for instance.

But that's exactly why the platform flag exists. Users can override that default behavior and I've done my best to make sure that is well documented.

If there's a bug where the compiler flat out doesn't work, we can address that. But it was expected that the auto detection might work but fall back to the slower JS version on some systems.

We want to make this as easy as possible for users, which means selecting good defaults. At the moment, this was the best I could come up for right now, but I'm continuing to monitor it.

**Comment by HitkoDev** [comment]
The way I see it, auto detection doesn't work - what works is the fact that
most users are able to use either of the three available compiler
implementations, which is mainly a lucky coincidence rather than a sign of
well-written code.
