### ISSUE TITLE
Compilation error comes up after enabling conformance checks

### ISSUE THREAD

**Issue by luzhang** [google/closure-compiler-npm#109]
Hey team,

I received this compilation error after enabling comformance checks in the compiler:
Compilation error: java.lang.RuntimeException: java.lang.RuntimeException: Generated message class "com.google.javascript.jscomp.Requirement" missing method "newBuilder".

Both Closure library and Closure compiler use '20180716.0.0' and I used following configurations.

const defaultFlags = {
  compilation_level: compilationLevel.ADVANCED,
  warning_level: 'VERBOSE',
  language_in: 'ECMASCRIPT_2017',
  language_out: 'ECMASCRIPT5',
  rewrite_polyfills: true,
  angular_pass: true,
  export_local_property_definitions: true,
  generate_exports: true,
  module_resolution: 'NODE',
  dependency_mode: 'STRICT',
  entry_point: 'app',
  output_wrapper: '(function(){\n%output%\n}).call(this)',
  js_output_file: 'main.min.js',
  externs: externsPath,
  conformance_configs: path.join(closureLibrarySrcDir, 'conformance_proto.txt'),
  jscomp_error: 'conformanceViolations',
};

I did not see this compilation error when Closure compiler is set to an older version like '20180506'. Can you share thoughts on it? 

Thanks!
Lu

**Comment by ChadKillingsworth** [comment]
Is this for the native version? Are you specifying a platform flag? If not, which OS are you using?

**Comment by luzhang** [comment]
Hey Chad,

No I did not specify platform flag so I assume it uses the OSX version by default since I am running it on MBP?

Thanks,
Lu

**Comment by ChadKillingsworth** [comment]
Yes - that means you are using the Graal image for OSX. I suspected that conformance configs might cause problems there, but I didn't have a test case that failed. I'll take a look.

**Comment by ChadKillingsworth** [comment]
Can you publish the contents of your `conformance_proto.txt` file?

**Comment by luzhang** [comment]
Hey Chad, we used the one in Closure dir:
https://github.com/google/closure-library/blob/master/closure/goog/conformance_proto.txt

**Comment by ChadKillingsworth** [comment]
@luzhang This is going to be really hard for me to debug. Here's my guess though - we need to add `com.google.javascript.jscomp.Requirement` to [the reflection config file](https://github.com/google/closure-compiler-npm/blob/f407d224ea4677f66d4e885e977f99ab8335936d/build-scripts/reflection-config.json).

**Comment by luzhang** [comment]
Thanks for looking into that Chad! Unfortunately I have no clue about it, let me know if you find out more after further tests.
