### ISSUE TITLE
v20190106 is not published to npm

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler-npm#127]
v20190106.0.0 is tagged in github, but not published to npm.
https://www.npmjs.com/package/google-closure-compiler

**Comment by brad4d** [comment]
Internal issue is http://b/122525761

**Comment by brad4d** [comment]
@ChadKillingsworth can you help out here?

Travis has 2 logs for the commit that created the release.
Both seem to say that publication was successful, though there is also a warning
`❌ missing dependencies - Version does not exist -`

Here's a link to one of the logs.
https://travis-ci.org/google/closure-compiler-npm/jobs/480674120#L1898

**Comment by ChadKillingsworth** [comment]
Sorry for the delay - I was behind on github notifications.

I pushed an empty commit which re-triggered Travis. It's not correctly published.

**Comment by brad4d** [comment]
@ChadKillingsworth did the "missing dependencies" error message actually indicate this failure?
Are there more instructions you could add to the release process doc that will help us catch this kind of problem and fix it more quickly in the future?

Thanks a bunch for fixing it this time.

**Comment by ChadKillingsworth** [comment]
>  did the "missing dependencies" error message actually indicate this failure?
It's always expected on one of the publishes, but it the missing dependency error on both the linux and OSX builds was the failure.

The trouble here is Graal can't be cross compiled. So one dependency has to be built on OSX and one on Linux - whichever one finishes last is supposed to publish the main package.

That being said - this is the first time this is happened. I'm going to monitor and see if it's a really rare fluke or occurs more often.
