### ISSUE TITLE
Travis build broken at 938a9cbe6bf79af04caa056af61ec8b97e0540f1

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler-npm#130]
Travis build passed before merging PR #129 , but still failed when the actual merge happened at
https://github.com/google/closure-compiler-npm/commit/938a9cbe6bf79af04caa056af61ec8b97e0540f1

Failure:
https://travis-ci.org/google/closure-compiler-npm/builds/501289352

Actually the Linux build job failed, but the Apple one passed.

**Comment by brad4d** [comment]
I clicked the "restart job" button in Travis, because I have some suspicion that the failure was a flake.

**Comment by brad4d** [comment]
Sure enough the rerun passed.
So, I'm changing the name of this issue to say that a flaky failure occurred.

@ChadKillingsworth I'm leaving this open so you can take a look.
Is it clear to you why the flake happened?
Thanks

**Comment by ChadKillingsworth** [comment]
No its not clear. Apparently hitting restart job also loses the build log so I can't even see which test failed.

**Comment by ChadKillingsworth** [comment]
I'm hoping this is closed by #131. If not, I'll revisit it.

**Comment by ChadKillingsworth** [comment]
This is still occurring.
