### ISSUE TITLE
Code splitting does not work when use Closure compiler with Gulp

### ISSUE THREAD

**Issue by luzhang** [google/closure-compiler-npm#133]
Hi,  I am trying the code splitting feature with Closure compiler. If I run the compiler in terminal, it outputs 2 files as expected.
`google-closure-compiler --module_resolution=NODE --js=src/js/child.js --chunk=child:1 --js=src/js/main.js --chunk=main:1:child --js_output_file=main.min.js  --compilation_level=ADVANCED`

But if I use the Gulp version of the compiler, it says "Module 'main' depends on unknown module 'child'. Be sure to list modules in dependency order."
```
const closureCompiler = require('google-closure-compiler').gulp();
gulp.src('./src/js/**/*.js', {base: './'})
  .pipe(closureCompiler({
      compilation_level: 'ADVANCED',
      module_resolution: 'NODE',
      entry_point: 'src/js/main',
      js: './src/js/child.js',
      chunk: 'child:1',
      js: './src/js/main.js',
      chunk: 'main:1:child',
      js_output_file: 'main.min.js',
}))
```

I am wondering why the behavior is different. Did I miss anything?

Thanks,
Lu

**Comment by luzhang** [comment]
Looks like the second 'js' and 'chunk' key overwrites the first one as it is object literal.
I have updated the configuration, but it complains 'Too many JS files specified. Expected 2 but found 4'.  Still no clues why it finds 4 JS files from src/js/.  Any thoughts is appreciated!
```
const closureCompiler = require('google-closure-compiler').gulp();
gulp.src('./src/js/**/*.js', {base: './'})
  .pipe(closureCompiler({
      compilation_level: 'ADVANCED',
      module_resolution: 'NODE',
      entry_point: 'src/js/main',
      js: ['./src/js/child.js',  './src/js/main.js'],
      chunk: ['child:1', 'main:1:child']
      js_output_file: 'main.min.js',
}))
```

**Comment by luzhang** [comment]
The problem is both JS files have been specified in gulp.src() and in the compiler config object as well. That leads to duplicate inputs for the compiler.

I removed the 'js' field from the compiler config, and only rely on the gulp.src to pipe those source files. The gulp task is able to run without error, it generates main.js and child.js. However, the code is not split correctly. The main.js includes everything while child.js only includes 'use strict'. 

Usually Closure compiler uses 'js' field to specify source files, but in this case it reads the stream from gulp.src, I wonder if that causes an issue so the compiler could not split the chunks correctly.

**Comment by ChadKillingsworth** [comment]
Code splitting with gulp does work - but it's hard to do correctly. You need to ensure that the files in stream are sorted correctly. Gulp will provide the JS files to the compiler - you need to provide the `chunk` flags.

I usually write a small custom gulp plugin to sort the files and insert that right before the compilation command:

```js
const {Transform} = require('stream');
class SortFiles extends Transform {
  constructor() {
    super({objectMode: true});
    this.fileCount = 0;
    this.files = [];
  }

  _transform(file, enc, cb) {
    this.fileCount++;
    this.files.push(file);
    cb();
  }

  _flush(cb) {
    this.files.sort((a, b) => b - a); // use your own custom sorting logic
    this.files.forEach(file => this.push(file));
    cb();
  }
}
```
