### ISSUE TITLE
How do I access non-contrib externs in npm module? 

### ISSUE THREAD

**Issue by rishipal** [google/closure-compiler-npm#143]
Original issue: https://github.com/google/closure-compiler/issues/3443
Moving it issue from closure-compiler to closure-compiler-npm with this issue.

from_original
{
How do I access https://github.com/google/closure-compiler/tree/master/externs from the distributed npm package? It seems like it's not included, and only the externs under contrib are.
}

**Comment by ChadKillingsworth** [comment]
The default externs are built into the compiler binaries. Typically they aren't needed directly by builds.

What's your use case for this?

**Comment by brad4d** [comment]
I believe this was fixed with https://github.com/google/closure-compiler-npm/pull/146
