### ISSUE TITLE
Yarn cannot install v20190729.0.0 of `google-closure-compiler-windows`

### ISSUE THREAD

**Issue by rsimha** [google/closure-compiler-npm#144]
Could it be that v20190729.0.0 of `google-closure-compiler-windows` wasn't published? See https://github.com/ampproject/amphtml/pull/23759#issuecomment-518878842

```
$ yarn
yarn install v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Lockfile has incorrect entry for "google-closure-compiler-windows@^20190729.0.0". Ignoring it.
Couldn't find any versions for "google-closure-compiler-windows" that matches "^20190729.0.0"
? Please choose a version of "google-closure-compiler-windows" from this list: (Use arrow keys)
❯ 20190801.0.0-nightly 
  20190731.0.0-nightly 
  20190730.0.0-nightly 
  20190729.0.0-nightly 
  20190728.0.0-nightly 
  20190727.0.0-nightly 
  20190726.0.0-nightly 
  20190725.0.0-nightly 
  20190724.0.0-nightly 
  20190723.0.0-nightly 
  20190722.0.0-nightly 
  20190721.0.0-nightly 
  20190720.0.0-nightly 
  20190719.0.0-nightly 
  20190718.0.0-nightly 
  20190717.0.0-nightly 
  20190716.0.0-nightly 
  20190715.0.0-nightly 
  20190714.0.0-nightly 
  20190713.0.0-nightly 
  20190712.0.0-nightly 
  20190711.0.0-nightly 
  20190710.0.0-nightly 
  20190709.0.0 
  20190709.0.0-nightly 
  20190708.0.0-nightly 
  20190707.0.0-nightly 
  20190706.0.0-nightly 
  20190705.0.0-nightly 
  20190704.0.0-nightly 
  20190703.0.0-nightly 
  20190702.0.0-nightly 
  20190701.0.0-nightly 
  20190630.0.0-nightly 
  20190628.0.0-nightly 
  20190618.0.0 
  20190528.1.0 
  20190528.0.0 
```

**Comment by z3t0** [comment]
Is there a temporary fix at the moment? Is there different version I can pin to

**Comment by lauraharker** [comment]
@EatingW this looks related to https://ci.appveyor.com/project/ClosureCompilerProject/closure-compiler-npm/branch/master

@z3t0 can you pin to version 20190709.0.0 ?

**Comment by EatingW** [comment]
@ChadKillingsworth I'm not really familiar with the Appveyor builds. It looks like Yarn install failed for Windows. Would you be able to take a look? Thanks!

**Comment by ChadKillingsworth** [comment]
I'm guessing a newer version of yarn was added to the base image at appveyor. I've updated the build script and it's now published successfully.

I'll have to manually build and publish the older versions that are missing.

**Comment by theseanl** [comment]
Just a heads up -- The same issue exists for the 20190909.0.0 version!

**Comment by ChadKillingsworth** [comment]
I just reran the build and it published. 🤷‍♂️
