### ISSUE TITLE
warnings_whitelist_file

### ISSUE THREAD

**Issue by crisgol** [google/closure-compiler-npm#165]
warnings_whitelist_file :'./scripts/whitelist.txt',

example  whitelist.txt

`'background.js:655?WARNING - [JSC_ARGUMENTS_CALLEE_FORBIDDEN] "arguments.callee" cannot be used in strict mode
scripts/background.js:613?WARNING - [JSC_ARGUMENTS_CALLEE_FORBIDDEN] "arguments.callee" cannot be used in strict mode
background.js:655?JSC_ARGUMENTS_CALLEE_FORBIDDEN
scripts/background.js:613?JSC_ARGUMENTS_CALLEE_FORBIDDEN
background.js:655?cannot be used in strict mode
scripts/background.js:613? WARNING - [JSC_ARGUMENTS_CALLEE_FORBIDDEN] "arguments.callee" cannot be used in strict mode`

not resolve warnings

**Comment by kjin** [comment]
Can you provide more details? All I can see is the warning `"arguments.callee" cannot be used in strict mode`. Are you using this value?

**Comment by lauraharker** [comment]
Like Kelvin said, could you provide more details?

Also, this issue should probably be on the [`main repo`](https://github.com/google/closure-compiler/wiki) unless it's specific to the npm release.

**Comment by concavelenz** [comment]
Please reopen if you can provide details.
