### ISSUE TITLE
Graal images are huge

### ISSUE THREAD

**Issue by ChadKillingsworth** [google/closure-compiler-npm#186]
After https://github.com/google/closure-compiler-npm/pull/174, the size of the native binary images is unacceptably large (approaching 200 MB).

The issue has been reported to the Graal project: https://github.com/oracle/graal/issues/2756

**Comment by concavelenz** [comment]
With the normal java build, we are able to see what is contributing by looking at the .jar.  Have you run into any similiar tooling for Graal?

**Comment by ChadKillingsworth** [comment]
I'm not really aware. A quick search found these options: https://gitter.im/graalvm/native-image?at=5bafc470e65a6343365ba56e

**Comment by teppeis** [comment]
Any progress?

This is a big problem for my project.
I'm using google-closure-compiler-linux in AWS Lambda for parallel builds, and 250MB is the upper limit of the whole package size after unzipping.
I cannot update Closure Compiler to v20200628+ for the limitation.

**Comment by smallshen** [comment]
https://github.com/upx/upx
On Windows it shrinks 40mb around to 11mb, I can make a pr

**Comment by ChadKillingsworth** [comment]
I have no experience with upx, but if it works and reduces size I am definitely for it. I'd welcome such a PR.
