### ISSUE TITLE
use installed binary closure-compiler.jar - avoid extra download

### ISSUE THREAD

**Issue by milahu** [google/closure-compiler-npm#192]
situation
i already have downloaded a closure-compiler-v20200830.jar

problem
i have very limited bandwidth and disk space

solution
find the closure-compiler-v*.jar file in my $PATH and use it
and only if not found, fall back to download

implementation
probably as npm post-install script
to generate an env.js file with paths to java and closure-compiler
or to native binary files, closure-compiler.exe etc

any interest in this feature?

**Comment by ChadKillingsworth** [comment]
The problem is now the downloaded compiler has no guarantees to be compatible with the npm repository itself. Can't this just be accomplished by globally installing the npm package? `npm install -g google-closure-compiler`

**Comment by ChadKillingsworth** [comment]
I've thought quite a bit about this and its simply something we don't want to support. We want to keep the npm package in sync with the compiler versions.
