### ISSUE TITLE
Gulp. The wrong error is displayed

### ISSUE THREAD

**Issue by trofim24** [google/closure-compiler-npm#195]
If an error occurred during initialization of VM `Could not reserve enough space for object heap` or insufficient memory for the Java Runtime Environment `Native memory allocation (malloc) failed`, then a general error is written [`"grunt-google-closure-compiler: Error parsing json encoded files"`](https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler/lib/gulp/index.js#L196)

**Comment by mprobst** [comment]
Assigning Chad to review the PR.
