### ISSUE TITLE
feature_request(grunt): generate source maps for all compiled files

### ISSUE THREAD

**Issue by Kristinita** [google/closure-compiler-npm#199]
### 1. Summary

It would be nice, if would be possible to generate simply add correct source map (sourcemap) for each compiled JavaScript file.

#### 2.1. Common cause

Implementation of a significant feature.

#### 2.2. Details

I couldn’t find any method, how I can generate source maps for all my JavaScript files, if I use Closure Compiler (see “Not helped” section).

### 3. Example of expected behavior

I migrated to Closure Compiler from the [**UglifyJS**](https://www.npmjs.com/package/uglify-js). UglifyJS have the `--source-map` option. See the [**description**](https://github.com/gruntjs/grunt-contrib-uglify#sourcemap) from the official grunt-contrib-uglify repository.

> If `true`, a source map file will be generated in the same directory as the `dest` file. By default it will have the same basename as the `dest` file, but with a `.map` extension.

For UglifyJS I need solely the `sourceMap: true` setting, and source maps will generate for all minified files. For example, UglifyJS create `KiraFirst.min.js.map` for `KiraFirst.min.js`, `KiraSecond.min.js.map` for `KiraSecond.min.js` and so on.

It would be nice to have a similar behavior for Closure Compiler.

#### 4.1. create_source_map

[**`create_source_map` option**](https://github.com/google/closure-compiler/wiki/Flags-and-Options#reports) create a single source map file. I couldn’t find, how I can create multiple source maps use this option.

#### 4.2. source_map_input

[**`source_map_input` option**](https://github.com/google/closure-compiler/wiki/Flags-and-Options#reports). [**Closure Compiler collaborator comment**](https://github.com/google/closure-compiler/issues/115#issuecomment-282808960):

> You can already use source maps in grunt. You just have to manually wire it all together. See the `--source_map_input` flag.

I have dozens of JavaScript files in my projects and I add new JavaScript files all the time. Manually adding files isn’t a best idea in this case. When I used UglifyJS, all I had to do was add `sourceMap: true`.

#### 4.3. Preserve source map comments

I can generate source map files when I compile CoffeeScript to JavaScript use [**`--map` or `--inline-map` flags**](https://coffeescript.org/#cli). `.js` files after a compilation have next lines in the end:

```js
//# sourceMappingURL=data:application/json;base64…
//# sourceURL=…
```

Closure Compiler remove these comments. I couldn’t find any method how I can preserve them.

#### 4.4. output_wrapper

Use [**`output_wrapper` option**](https://github.com/google/closure-compiler/wiki/Flags-and-Options#output) I can add to the end of each JavaScript file the line `//# sourceMappingURL=output.min.js.map`. But I couldn’t find how I can add the line `//# sourceMappingURL={current_file}.min.js.map` where `{current_file}` is the name of a current file without the extension. I couldn’t find how I can reference the source maps generated by CoffeeScript.

#### 4.5. Use a bundler

+ [**Bad source maps caused by multiple transformations**](https://blog.sentry.io/2018/10/18/4-reasons-why-your-source-maps-are-broken#bad-source-maps-caused-by-multiple-transformations):

    > If you’re using *two or more JavaScript compilers* invoked separately (e.g., Babel + UglifyJS), it’s possible to produce a source map that points to an intermediate transformed state of your code, rather than the original source code. This means that when you debug in the browser, the code you’re stepping through isn’t minified — an improvement for sure — but it’s still not a 1:1 match with your original source code. (…)
    >
    > Use a bundler like Webpack to manage all your transformations
    >
    > Instead of using Babel or UglifyJS separately, use them instead as Webpack plugins (e.g., babel-loader and uglifyjs-webpack-plugin). Webpack will produce a single source map that transforms from the final result back to your original source code, even though there are multiple transformations taking place under the hood. (…)
    >
    > If you have a choice in the matter, we’d recommend pursuing the first option — just use Webpack and save yourself some grief.

I couldn’t find how I can do it use Grunt + CoffeeScript + Closure Compiler.

#### 4.6. External tools

I couldn’t find third-party Grunt plugins specifically for source maps generation.

### 5. Environment

(For preventing an [**XY problem**](https://xyproblem.info/))

I’m working with JavaScript with these tools:

1. [**CoffeeScript**](https://coffeescript.org/): `KiraSrc.coffee` → `KiraDest.js`
1. Closure Compiler (I migrated from UglifyJS that doesn’t support ES2015 and above): `KiraDest.js` → `KiraDest.min.js`
1. [**grunt-cache-bust**](https://github.com/benhoIIand/grunt-cache-bust): `Kira.min.js` → `Kira.min.4147kira1447godd.js`
1. [**merge-source-maps**](https://www.npmjs.com/package/merge-source-maps): create `Kira.min.4147kira1447godd.js.map` file.

It would be nice to comply with all requirements described in the “[**4 Reasons Why Your Source Maps are Broken**](https://blog.sentry.io/2018/10/18/4-reasons-why-your-source-maps-are-broken)” article. It would be nice to debug a `KiraSrc.coffee` file in a browser when `<script src="Kira.min.4147kira1447godd.js.map" defer></script>` in a HTML file.

If it’s possible without any improvements, please tell me what should I do.

Thanks.

**Comment by ChadKillingsworth** [comment]
This isn't grunt specific. Can you post this in the main compiler repo?

What's needed is for the output wrapper function to have placeholder expansion support for the output filename itself. That's not there today, but a worthwhile request.
