### ISSUE TITLE
Wrong type for compiler constructor

### ISSUE THREAD

**Issue by evmar** [google/closure-compiler-npm#21]
The args are defined as

``` js
 * @param {Object<string,string>|Array<string>} args
```

But as you can see here, the values of the Object can themselves be arrays:

https://github.com/ChadKillingsworth/closure-compiler-npm/blob/c7c177e7255f7abb523490c8b2e615e11d102667/lib/node/closure-compiler.js#L45

**Comment by ChadKillingsworth** [comment]
I'm sure there are quite a few JSDoc problems here. The compiler isn't actually used to type check this because nodejs code isn't very usable with the compiler.

**Comment by ChadKillingsworth** [comment]
Nobody is currently working on this nor is it even a priority. I'm closing this for now.
