### ISSUE TITLE
Support arm64 on darwin

### ISSUE THREAD

**Issue by domoritz** [google/closure-compiler-npm#211]
It would be great if you could support ARM64 (Apple M1) for the OSX bundles.

**Comment by ChadKillingsworth** [comment]
Will be quite a while before that is possible. Graal has to support building in that environment and we would need an automated build system that supports M1 macs.

**Comment by domoritz** [comment]
Is that https://github.com/oracle/graal/issues/2666?

**Comment by ChadKillingsworth** [comment]
That looks correct for the Graal support. But we would still need a build environment. GitHub Actions doesn't support M1 macs right now.

**Comment by domoritz** [comment]
The relevant issue for that is https://github.com/actions/virtual-environments/issues/2187, I believe.

**Comment by ChadKillingsworth** [comment]
We can probably add arm64 to the architecture though and let Rosetta handle the translation for now. Would you be able to test that the current image actually works? I don't have an M1 Mac to try this on.

**Comment by domoritz** [comment]
Yes, I'd be happy to give it a try.

**Comment by ChadKillingsworth** [comment]
You can download the MacOS image binary from any of the CI build runs such as https://github.com/google/closure-compiler-npm/actions/runs/860306976

You just need to see if the binary will execute. So `compiler --help` should do it.

**Comment by domoritz** [comment]
I downloaded the binary, marked it as executable, allowed it in the macOS security settings and ran `./compiler --help` without problems. 

```
$ arch
arm64
$ lipo -info compiler
Non-fat file: compiler is architecture: x86_64
```

So looks like it should just work.

**Comment by domoritz** [comment]
Anything else I can help with @ChadKillingsworth?

**Comment by domoritz** [comment]
@ChadKillingsworth anything else I can test before you make a release?

**Comment by ChadKillingsworth** [comment]
I created the pr.

**Comment by domoritz** [comment]
Thank you. I made a similar pull request in #215.

**Comment by ChadKillingsworth** [comment]
Awe sorry - I missed that one.

**Comment by ChadKillingsworth** [comment]
You should be able to test this tomorrow with the nightly build

**Comment by domoritz** [comment]
Thanks for merging. I totally forgot to mention it here. Looking forward to trying the new version.
