### ISSUE TITLE
Windows native image build is broken

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler-npm#218]
As of at least 18 days ago the Windows native image build has been broken.

https://github.com/google/closure-compiler-npm/runs/3028842102?check_suite_focus=true#logs

**Comment by brad4d** [comment]
The last successful build was on July 8
https://github.com/google/closure-compiler-npm/actions/runs/1011545454 

The first failed build was July 9
http://go/gh/google/closure-compiler-npm/actions/runs/1015080298

These were daily scheduled builds.
We haven't committed a change to the repo since June 30.

So it seems that something spontaneously broke unrelated to our changes.

**Comment by mprobst** [comment]
Internal issue: http://b/194984781

I suspect this is an open source sync issue where we're missing a specific file in the sync. We need to figure out how this is supposed to work.

**Comment by brad4d** [comment]
This was fixed by @nreid260 with https://github.com/google/closure-compiler-npm/commit/376824f42074688a630bcf9521d96ded81fd9fc5

Thanks, Nick!
