### ISSUE TITLE
v20220405 doesn't include LICENSE file

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler-npm#236]
From v20220405, google-closure-compiler and the other google-closure-compiler-* packages don't include the LICENSE file.
Until v20220301, they had it.

**Comment by h-joo** [comment]
Internal Google issue http://b/229680735 created.

**Comment by rishipal** [comment]
I downloaded the compiler v20220405 from the below links and can see that they all contain the LICENSE file. 
 
- https://www.npmjs.com/package/google-closure-compiler 
- https://github.com/google/closure-compiler-npm/tags
- https://github.com/google/closure-compiler/tags 

In which download are you seeing the file missing?

**Comment by teppeis** [comment]
@rishipal run `npm i google-closure-compiler` and check the installed `node_modules` directory.
also you can confirm this issue via npmfs:
https://npmfs.com/package/google-closure-compiler/20220405.0.0/
https://npmfs.com/package/google-closure-compiler/20220301.0.0/

**Comment by teppeis** [comment]
FYI
- https://npmfs.com/package/google-closure-compiler/20220403.0.0-nightly/ includes LICENSE
- https://npmfs.com/package/google-closure-compiler/20220404.0.0-nightly/ doesn't include LICENSE

**Comment by rishipal** [comment]
The maven releases contains the LICENSE. Looks like this problem only happens for npmfs. 

I don't see any changes in the npm release process instructions. https://github.com/google/closure-compiler-npm/blob/master/deployments.md#deploying-new-releases-of-the-main-compiler

**Comment by teppeis** [comment]
@ChadKillingsworth @rishipal 
This problem has not yet been resolved in v20220502.0.0.
v20220502.0.0 does not include LICENSE.
You can confirm with `npm i google-closure-compiler` or download https://registry.npmjs.org/google-closure-compiler/-/google-closure-compiler-20220502.0.0.tgz .

#237 added LICENSE with symlinks but I think `npm pack` does not follow symlinks.
