### ISSUE TITLE
compile to native wasm

### ISSUE THREAD

**Issue by jimmywarting** [google/closure-compiler-npm#245]
can you compile a version that outputs wasm binaries and isn't tied to windows, mac or linux?

**Comment by gunan** [comment]
Thanks for the suggestion.
While we see that this could be useful, we do not have the bandwidth to make this happen right now.
However, we would gladly accept this as a contribution from the community.

**Comment by ChadKillingsworth** [comment]
Unfortunately, Graal native images do not support wasm. Here's the tracking issue on the Graal side: https://github.com/oracle/graal/issues/3391

We can reopen this discussion after Graal has support, but until then there just isn't a path forward.
