### ISSUE TITLE
bump the node engine version

### ISSUE THREAD

**Issue by jimmywarting** [google/closure-compiler-npm#252]
14 is currently the LTS version. what do you feel about bumping it to a higher version in order to use newer js features?

https://github.com/google/closure-compiler-npm/blob/268f16b6bd91f02bf42c15fcaa04fe6f30a71387/packages/google-closure-compiler/package.json#L66-L68

**Comment by ChadKillingsworth** [comment]
Yes it's OK to set the min supported version to Node 14. The CI jobs are already Node 14+.
