### ISSUE TITLE
why include gulp/vinyl?

### ISSUE THREAD

**Issue by jimmywarting** [google/closure-compiler-npm#253]
it was decades ago since gulp was kind of mainstream. right now it feels a bit old school-ish to still use it when there are newer more awesome build packages out there. like webpack, rollup to mention a few.

right now it only feels like you are shipping stuff to us that we don't really need anymore... so it waste time to install those packages as well.

could it maybe be fleshed out into a own separate package instead maybe?

**Comment by ChadKillingsworth** [comment]
Gulp is still used. I personally have projects still using it. While there are more integrated and popular build systems, they are not a direct replacement for tools like Gulp. Splitting into a separate repo is a considerable amount of work, both initially and in terms of long term maintenance. I'm not really open to do doing that right now without a compelling reason.

Gulp itself isn't a dependency of the project - just Vinyl which is simply used to represent a "file" which never existed on disk.

**Comment by jimmywarting** [comment]
hmm, yea... i'm casting a googling 👀 on Vinyl as something abnormal. never really been a fan of vinyl

Blob and Files should have been introduced much earlier in NodeJS and also have a way of getting such files backed up by the disk that dose not allocate any memory... with Files you can construct in memory files too that don't exist on the disk.

NodeJS now have both Blob and Files and also an open issue on getting blobs backed up by the file system
