### ISSUE TITLE
Nightly Build reported as a virus by Google AV

### ISSUE THREAD

**Issue by mensfeld** [google/closure-compiler-npm#260]
Hey, this is probably an issue in the reporting but I wanted to give you a heads-up:

google-closure-compiler-windows - 20220926.0.0-nightly from NPM is reported as malicious by Google itself based on VirusTotal and recently updated Clamdscan signatures:

https://www.virustotal.com/gui/file/f2240b4e123fce798697e7a514fde2e0d1382d4612514cbcd25683af856ac791/detection

Raising this issue since it's Google complaining on Google

![Zrzut ekranu z 2022-09-26 15-31-34](https://user-images.githubusercontent.com/392754/192289818-3bc8edf4-86c3-4045-99c0-179686b81b0c.png)

**Comment by ChadKillingsworth** [comment]
Interesting - this could be fun to track down.

**Comment by gunan** [comment]
Thanks for reporting.
This is pretty black box to me. I do not have prior experience with this website or the security scanning service provided by google.
Is there more information on the service, or an escalation path provided for such cases?

**Comment by mensfeld** [comment]
@gunan I have no idea how that works. The only thing I know is that virustotal is owned by google.

**Comment by ChadKillingsworth** [comment]
Just as an update, we're fairly certain this is a false positive, but to date none of us have found a way to report or address the issue with Virus Total.

**Comment by mensfeld** [comment]
@ChadKillingsworth had the same problem. Really hard to figure out how to reach them about a particular issue...
