### ISSUE TITLE
`GLIBC_2.32' not found error in Ubuntu 20.04

### ISSUE THREAD

**Issue by teppeis** [google/closure-compiler-npm#272]
From `20221115.0.0-nightly`, `google-closure-compiler-linux` throws an error in Ubuntu 20.04.

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found
```

The build environment was updated to Ubuntu 22.04 from `20221115.0.0-nightly`:
https://github.com/google/closure-compiler-npm/actions/runs/3470258791/jobs/5798561458#step:1:8

Ubuntu 20.04 was used until `20221114.0.0-nightly`:
https://github.com/google/closure-compiler-npm/actions/runs/3461297839/jobs/5778886771#step:1:8

**Comment by teppeis** [comment]
This is the cause.

[GitHub Actions: Ubuntu-latest workflows will use Ubuntu-22.04 \| GitHub Changelog](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/)

**Comment by ChadKillingsworth** [comment]
Looks like GRAAL has a fix for this in general. Also makes me wonder if that's what is causing #265

**Comment by ChadKillingsworth** [comment]
You might give the binary found at the bottom of https://github.com/google/closure-compiler-npm/actions/runs/3482892969 a try. If that fixes it, once merged I'll do a patch release.

**Comment by teppeis** [comment]
@ChadKillingsworth It works in ubuntu 20.04. Thank you!
