### ISSUE TITLE
Compiler release workflow doesn't publish the latest version to npm

### ISSUE THREAD

**Issue by frigus02** [google/closure-compiler-npm#285]
We just noticed our most recent release didn't get pushed to npm. It seems the release workflow lost track of the version number somewhere.

https://github.com/google/closure-compiler-npm/actions/runs/4312425340

- The "Create release" job created v20230228.0.0
- The "Publish Packages" job says "Already published google-closure-compiler 20230206.0.0"

@ChadKillingsworth, do you have an idea where things went wrong?

**Comment by frigus02** [comment]
It looks like for some reason the build workflow didn't checkout the latest commit: https://github.com/google/closure-compiler-npm/actions/runs/4312425340/jobs/7523068378#step:4:255

**Comment by ChadKillingsworth** [comment]
GitHub always uses the same commit sha for re-used workflows and I haven't been able to work around it. I'm updating the release instructions to add an additional step to publish the new commit.
