### ISSUE TITLE
Unsupported platform ia32

### ISSUE THREAD

**Issue by ckir** [google/closure-compiler-npm#292]
Running ```npm install google-closure-compiler-linux``` I get:

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for google-closure-compiler-linux@20230502.0.0: wanted {"os":"linux","cpu":"x32,x64"} (current: {"os":"linux","cpu":"ia32"})
npm ERR! notsup Valid os:   linux
npm ERR! notsup Actual os:  linux
npm ERR! notsup Valid cpu:  x32,x64
npm ERR! notsup Actual cpu: ia32
```
Is it possible to fix that?

**Comment by gunan** [comment]
Unfortunately, we have no plans to extend support to other platforms for the native binaries.
We recommend using the java version for unsupported platforms. Java version should work for all platforms that have an appropriate JVM is available. You can install the java version of the compiler with this package:

https://www.npmjs.com/package/closure-compiler
