### ISSUE TITLE
feature request: add support of arm64 architecture on macOS

### ISSUE THREAD

**Issue by 0xWOF** [google/closure-compiler-npm#296]
`closure-compiler-npm` currently only support amd64 architecture on macOS.
Of course arm64 machine can use `closure-compiler-npm` through rosetta2.
But it would be great if `closure-compiler-npm` can directly support arm64 architecture on macOS.

**Comment by ChadKillingsworth** [comment]
This won't be possible until GitHub supports MacOS runners with an arm64 architecture or Graal supports cross-compilation.

See https://github.com/oracle/graal/issues/407

**Comment by ChadKillingsworth** [comment]
Duplicate of #291

**Comment by 0xWOF** [comment]
@ChadKillingsworth FYI: GitHub supports macOS runner with arm64 architecture for paid user (not for free user)
- link: <https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/>

**Comment by 0xWOF** [comment]
Hello, @ChadKillingsworth, GitHub start to support macOS runner with arm64 architecture for open source project. It can be used with `runs-on: macos-14`.
- Warning: `macos-12`, `macos-13` is **amd64** architecture and `macos-14` is arm64 architecture. GitHub seems stop support **amd64** architecture from `macos-14`.

Link: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
