### ISSUE TITLE
Publish new release to NPM?

### ISSUE THREAD

**Issue by codyebberson** [google/closure-compiler-npm#299]
Do you plan to publish the most recent release to NPM?

Most recent release is version `20231112.0.0`: https://github.com/google/closure-compiler-npm/releases/tag/v20231112.0.0

Last published NPM version is `20230802.0.0`: https://www.npmjs.com/package/google-closure-compiler?activeTab=versions

Thanks!

**Comment by rishipal** [comment]
Google internal issue created - b/324501531

**Comment by brad4d** [comment]
PR #300 turned back on the nightly pushes.
We're not quite ready to do another full release yet.
