### ISSUE TITLE
Does google/closure-compiler need to depend on google/closure-compiler-npm ?

### ISSUE THREAD

**Issue by brad4d** [google/closure-compiler-npm#302]
There's currently a dependency from `closure-compiler` to `closure-compiler-npm` defined here.

https://github.com/google/closure-compiler/blob/564c23785c6e9f83a1dcf4f6c6bf41bc4301cc49/package.json#L11

@ChadKillingsworth what is this dependency for?
Is it actually needed?

**Comment by ChadKillingsworth** [comment]
It was done to ensure that the compiler wasn't breaking the npm integration. It basically runs the tests from the npm project in the main repo. https://github.com/google/closure-compiler/blob/564c23785c6e9f83a1dcf4f6c6bf41bc4301cc49/.github/workflows/ci.yaml#L93
