### ISSUE TITLE
`google-closure-compiler-osx/compiler` in v20240317.0.0 detected as malware by VirusTotal

### ISSUE THREAD

**Issue by cpcallen** [google/closure-compiler-npm#310]
Per corp policy I uploaded `node_modules/google-closure-compiler-osx/compiler` to VirusTotal before upvoting in Santa.  [It triggered the Kingsoft malware detector for something called Script.Ks.Malware.6977](https://www.virustotal.com/gui/file/c002ab76eb1912481e93c0544f451601eb975783c91947d0d1c44c4b760d7b4d?nocache=1).

<img width="1070" alt="Screenshot 2024-07-10 at 12 41 39" src="https://github.com/google/closure-compiler-npm/assets/5603958/99925c47-ef38-4231-914c-b16d3b6de8a9">

I re-ran the analysis just to make sure it wasn't a fluke (the original analysis had taken much longer than usual and I wondered if this failure was actually due to a timeout of some kind) but the result the second time was identical.

I suspect this is a false positive but I'm not able to establish exactly what is triggering the detector.

**Comment by ChadKillingsworth** [comment]
This has occurred before https://github.com/google/closure-compiler-npm/issues/260

It's very frustrating, but we've had little success in getting these addressed.

**Comment by cpcallen** [comment]
Unfortunate.  No problem if you want to just close this report.  The issue is not causing a problem, just something I thought you might want to be aware of.

**Comment by ChadKillingsworth** [comment]
I did go check to see if I could find somewhere to report a false positive to Kingsoft. I didn't find anything.
