### ISSUE TITLE
Type Warnings

### ISSUE THREAD

**Issue by camronlent** [google/closure-compiler-npm#54]
I finally found the option to output type errors (jscomp_warning=reportUnknownTypes), and I was able to add type declarations to my whole project (pet project admittedly). I get the following output from running the compiler though. Is there a way to omit the internal type warnings? I really want to get it to say 100%... unless it's my code that I need to change to get the [synthetic:xyz] warnings to go away, in which case I have no idea how to track them down =\.

P.S. I am running this through gulp if that makes a difference.

[synthetic:es6/array/find] :34: WARNING - could not determine the type of this expression
    return $jscomp.findInternal(this, callback, opt_thisArg).v;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 [synthetic:es6/array/find] :34: WARNING - could not determine the type of this expression
    return $jscomp.findInternal(this, callback, opt_thisArg).v;
                                                ^^^^^^^^^^^

 [synthetic:es6/array/values] :31: WARNING - could not determine the type of this expression
    return $jscomp.iteratorFromArray(this, function(k, v) { return v; });
                                                                   ^

 [synthetic:es6/util/iteratorfromarray] :23: WARNING - could not determine the type of this expression
$jscomp.array = $jscomp.array || {};
                ^^^^^^^^^^^^^

 [synthetic:es6/util/iteratorfromarray] :43: WARNING - could not determine the type of this expression
        return {value: transform(index, array[index]), done: false};
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 [synthetic:es6/util/iteratorfromarray] :46: WARNING - could not determine the type of this expression
      return iter.next();
             ^^^^^^^^^^^

 [synthetic:es6/util/iteratorfromarray] :49: WARNING - could not determine the type of this expression
  iter[Symbol.iterator] = function() { return iter; };
       ^^^^^^^^^^^^^^^

 [synthetic:util/checkstringargs] :28: WARNING - could not determine the type of this expression
  if (thisArg == null) {
      ^^^^^^^

 [synthetic:util/checkstringargs] :38: WARNING - could not determine the type of this expression
  return thisArg + '';
         ^^^^^^^

 [synthetic:util/defineproperty] :41: WARNING - could not determine the type of this expression
      descriptor = /** @type {!ObjectPropertyDescriptor} */ (descriptor);
                                                             ^^^^^^^^^^

 [synthetic:util/defineproperty] :45: WARNING - could not determine the type of this expression
      if (target == Array.prototype || target == Object.prototype) return;
          ^^^^^^

 [synthetic:util/defineproperty] :45: WARNING - could not determine the type of this expression
      if (target == Array.prototype || target == Object.prototype) return;
                                       ^^^^^^

 [synthetic:util/defineproperty] :46: WARNING - could not determine the type of this expression
      target[property] = descriptor.value;
      ^^^^^^

 [synthetic:util/findinternal] :41: WARNING - could not determine the type of this expression
    if (callback.call(thisArg, value, i, array)) return {i: i, v: value};
                      ^^^^^^^

 [synthetic:util/findinternal] :41: WARNING - could not determine the type of this expression
    if (callback.call(thisArg, value, i, array)) return {i: i, v: value};
                               ^^^^^

 [synthetic:util/findinternal] :41: WARNING - could not determine the type of this expression
    if (callback.call(thisArg, value, i, array)) return {i: i, v: value};
                                                                  ^^^^^

 [synthetic:util/global] :31: WARNING - could not determine the type of this expression
  return (typeof window != 'undefined' && window === maybeGlobal) ?
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 [synthetic:util/global] :33: WARNING - could not determine the type of this expression
      (typeof global != 'undefined' && global != null) ? global : maybeGlobal;
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 [synthetic:util/global] :33: WARNING - could not determine the type of this expression
      (typeof global != 'undefined' && global != null) ? global : maybeGlobal;
              ^^^^^^

 [synthetic:util/global] :33: WARNING - could not determine the type of this expression
      (typeof global != 'undefined' && global != null) ? global : maybeGlobal;
                                       ^^^^^^

 [synthetic:util/global] :33: WARNING - could not determine the type of this expression
      (typeof global != 'undefined' && global != null) ? global : maybeGlobal;
                                                         ^^^^^^

 [synthetic:util/polyfill] :32: WARNING - could not determine the type of this expression
  var obj = $jscomp.global;
            ^^^^^^^^^^^^^^

 [synthetic:util/polyfill] :36: WARNING - could not determine the type of this expression
    if (!(key in obj)) obj[key] = {};  // Might want to be defineProperty.
                 ^^^

 [synthetic:util/polyfill] :36: WARNING - could not determine the type of this expression
    if (!(key in obj)) obj[key] = {};  // Might want to be defineProperty.
                       ^^^

 [synthetic:util/polyfill] :37: WARNING - could not determine the type of this expression
    obj = obj[key];
    ^^^

 [synthetic:util/polyfill] :37: WARNING - could not determine the type of this expression
    obj = obj[key];
          ^^^

 [synthetic:util/polyfill] :40: WARNING - could not determine the type of this expression
  var orig = obj[property];
             ^^^

 [synthetic:util/polyfill] :41: WARNING - could not determine the type of this expression
  var impl = polyfill(orig);
                      ^^^^

 [synthetic:util/polyfill] :42: WARNING - could not determine the type of this expression
  if (impl == orig || impl == null) return;
              ^^^^

 [synthetic:util/polyfill] :44: WARNING - could not determine the type of this expression
      obj, property, {configurable: true, writable: true, value: impl});

**Comment by MatrixFrog** [comment]
We don't generally recommend using `reportUnknownTypes` but since all those are in synthetic code I suppose we can add suppressions for them.

**Comment by camronlent** [comment]
That would be awesome ^_^

**Comment by ChadKillingsworth** [comment]
This looks to be fixed by google/closure-compiler@8fa984c

If not, the bug can be re-opened on the main compiler repo as it doesn't relate to any of the npm plugins or publication.
