### ISSUE TITLE
[Request]: Add webpack integration with Closure Compiler

### ISSUE THREAD

**Issue by TheLarkInn** [google/closure-compiler-npm#56]
Hi all! Sean from the [webpack](http://github.com/webpack/webpack) team. We've had quite a few features in our upcoming [milestones](https://github.com/webpack/webpack/milestones) and [voting page](https://webpack.js.org/vote) that we believe could be solved by a special integration from webpack to Closure Compiler.

@ChadKillingsworth, it was a pleasure discussing this topic with you and you seemed pretty confident that this is doable. This integration would look similar to the --module flag but instead we would provide (via a plugin, or cli api for CC) access to the dependency graph that webpack generates. 

Some MVP Features we wanted to serve as the baseline (and maybe for our testing purposes after the integration is added is) is that in some way it can support webpack's code splitting feature. 

GCC (from my understanding), used standalone, needs to have paths to files and split points provided via flags or a configuration to perform the node module resolution process. The good news is that webpack when running, will have already resolved, encapsulated, and created a dependency graph in memory (`compilation`), which has all of this information already provided. 

### Option 1 (currently only option I can think of): GCC consumes already created files from webpack
Some examples of webpack output might look like something seen [here](https://github.com/jhnns/webpack-perf-examples/blob/master/examples). In fact I think each of these examples are the most basic that folks will come across, and are create use cases to test against. 

In each example you will see a `/bundles/` directory where the build output for each project resides. Each bundle represents what we call a _Chunk_ in webpack. The normal require statements -- when webpack creates a bundle -- will be replaced with a browser compatible module system (`__webpack_require__`). A new dependency type can be created in GCC to map and register --modules so that closure compiler can understand them.

#### Before webpack applies module/dependency templates:
```js
Promise.all([
    System.import("./b"),
    System.import("./c")
]).then((b, c) => {
    console.log(b, c);
});
```

#### After webpack applies module/dependency templates:
```js
/******/ ({
/***/ 2:
/***/ function(module, exports, __webpack_require__) {

Promise.all([
    // Says "Access async chunk with ID 1, and then fetch module ID 0" 
   // (this is code splitting so returns promise)
    __webpack_require__.e/* System.import */(1).then(__webpack_require__.bind(null, 0)), 
    __webpack_require__.e/* System.import */(0).then(__webpack_require__.bind(null, 1))
]).then((b, c) => {
    console.log(b, c);
});

/***/ }
/******/ });
```

As seen above, this is using the ESM Harmony Module spec (imports/exports), as well as Code Splitting. Instead of having to go through the secondary node_module resolution, etc we should be able to use the module pattern we have defined to process these modules successfully. This [MainTemplate](https://github.com/webpack/webpack/blob/master/lib/MainTemplate.js#L12-L24) class includes a mapping to what each property on `__webpack_require__` does and can be used to aid in translating the different kinds. 

Of course we are 100% willing to assist with this feature, whether it be support etc.

**Comment by ChadKillingsworth** [comment]
Ideally, we could use the chunks before the templates are applied. I'm poking around the webpack source to find the best lifecycle event to wire to for this. I'll to be able to produce a list of files (in memory) in source order (entry point last - leaf nodes of the tree first).

**Comment by TheLarkInn** [comment]
Yes that is option two but didn't know what would be easier. Let us know where and how we can help.

**Comment by ChadKillingsworth** [comment]
If you can help get me a structure something like below, then I can move over to the compiler part:

```js
class ClosureCompilerPlugin {
  apply(compiler) {
    compiler.plugin("compilation", (compilation) => {
      compilation.plugin("before-module-assets", () => {
        // need to obtain something like ...
        let chunks = [{
          filename: 'chunk1.js',
          sources: [{
            filename: './c.js',
            content: 'exports.exportA = "exportA";\nexports.exportB = "exportB";'
          }, {
            filename: './b.js',
            content: 'module.exports = "b export";'
          }, {
            filename: './a.js',
            content: 'const b = require("./b.js");\nconst c = require("./c.js");\n\nconsole.log(b, c.exportA, c.exportB);'
          }];
        }];
      });
    });
  }
}
```

**Comment by TheLarkInn** [comment]
Can certainly do that.

**Comment by TheLarkInn** [comment]
Alright this should yield for you the results that you are looking for:

```javascript
class ClosureCompilerPlugin {
    apply(compiler) {
        compiler.plugin("compilation", (compilation) => {
            const compilationInstance = compilation;

            compilation.plugin("before-module-assets", () => {
                const closureCompatChunks = compilation.chunks.map(chunk => {
                    return {
                        name: chunk.name,
                        id: chunk.id,
                        sources: chunk.modules.map(module => {
                            return module._source;
                        })
                    };
                });

                console.log(closureCompatChunks);
            });
        });
    }
}
module.exports = ClosureCompilerPlugin;
```

**Comment by ChadKillingsworth** [comment]
Initial work pushed to the [webpack branch](https://github.com/google/closure-compiler-npm/tree/webpack).

Currently blocked on google/closure-compiler#2327. It will be a bit before I can get to that.

**Comment by thelgevold** [comment]
Hi, Any progress on Webpack integration with Closure compiler?

**Comment by ChadKillingsworth** [comment]
Major questions / blockers left:

 - How to get the full dependency graph and resolutions to closure-compiler? When the compiler sees `require('foo')`, it has to know what file that relates to. Normally this requires the full node module resolution algorithm in which the package.json files play a part.
 - Figure out how to provide the compiler with the chunk splits and which modules cross a chunk boundary. Any module which is only used within a single chunk can be completely optimized to a script (no longer even a module).
 - Add support for the dynamic import statement to the compiler.

**Comment by TheLarkInn** [comment]
> How to get the full dependency graph and resolutions to closure-compiler? When the compiler sees require('foo'), it has to know what file that relates to. Normally this requires the full node module resolution algorithm in which the package.json files play a part.

So depending on where you are consuming this information, webpack's module instance has the fully resolved path information already added to it (as it is necessary steps of the resolver and module factory before the module source can be collected and it's object created in mem). 

> Figure out how to provide the compiler with the chunk splits and which modules cross a chunk boundary. Any module which is only used within a single chunk can be completely optimized to a script (no longer even a module).

So there would be ways to do this in theory. One would be to read the DependenciesBlock that live on an existing block. Whenevee one Module has a blocks array with values that means it has deps that are code split into separate chunks.

**Comment by jmooradi** [comment]
I'm trying out the webpack-beta branch and I'm seeing this error come up a lot:

ERROR in closure-compiler: java.lang.IllegalArgumentException: Multiple entries with same key: 1=/path/file.js and 1=/path/file.js

The key and the filename are always the same, is this related to not supporting dynamic imports or just a need to merge common entries?

**Comment by steve-todorov** [comment]
@ChadKillingsworth is the repo public? I have been keeping an eye on this for a while and would like to continue being in the loop :)

**Comment by ChadKillingsworth** [comment]
@steve-todorov Not yet. Invite sent.

**Comment by ChadKillingsworth** [comment]
Work for this has moved to https://github.com/webpack-contrib/closure-webpack-plugin

**Comment by steve-todorov** [comment]
Thank you very much for the invitation and making the repo public! :)
