### ISSUE TITLE
[bug?] polyfils in the beginning of the output

### ISSUE THREAD

**Issue by orenmizr** [google/closure-compiler-npm#59]
how to remove ? might be related to - ampproject/amphtml#4933
```
var f;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function n(){n=function(){};m.Symbol||(m.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function p(){n();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return q(this)}});p=function(){}}function q(a){var b=0;return da(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function da(a){p();a={next:a};a[m.Symbol.iterator]=function(){return this};return a}var r={};Object.defineProperty(r,"__esModule",{value:!0});function u(){
```

**Comment by MatrixFrog** [comment]
To remove the polyfills you can pass `--rewrite_polyfills=false`. Though, it looks like some of the code there is not polyfills, but other support code for ES6-to-ES5 transpilation.

**Comment by samccone** [comment]
even with -rewrite_polyfills=false it seems like this code is still included, hmm

**Comment by ChadKillingsworth** [comment]
It's the ES6 runtime. Don't think it can be excluded. In any case - this would be an issue for https://github.com/google/closure-compiler as it's not specific to the npm distribution.

**Comment by samccone** [comment]
yep, thanks @ChadKillingsworth I just found the cause of this to be using the spread operator :) once I got rid of that the polyfill code went away \o/

**Comment by MatrixFrog** [comment]
I'm working on outputting ES6 which will eliminate the runtime library and eventually produce smaller code too. In the meantime, the runtime library is a constant size so I would encourage you to consider if the less convenient developer experience from avoiding spreads and other ES6 features is worth the code size improvement.

**Comment by ChadKillingsworth** [comment]
Sometimes it's worth it in small files that are compiled standalone. I have a bootstrap file that calculates needed polyfills - I try to avoid ES6 there.
