### ISSUE TITLE
Duplicate input errors when similar paths are matched by gulp globs

### ISSUE THREAD

**Issue by nckh** [google/closure-compiler-npm#62]
```
const gulp = require('gulp');
const closureCompiler = require('google-closure-compiler').gulp();

const paths = [
  '../lib1/**/*.js',
  '../lib2/**/*.js',
  'main.js',
];

const flags = {
  compilation_level: 'ADVANCED',
  language_in: 'ECMASCRIPT6_STRICT',
  language_out: 'ECMASCRIPT5',
  entry_point: 'app',
  js_output_file: 'main.min.js'
};

gulp.task('js', function() {
  return gulp.src(paths)
      .pipe(closureCompiler(flags))
      .pipe(gulp.dest('js'));
});
```

If two JS files share the same relative path under lib1/ and lib2/ (here lib1/array/array.js and lib2/array/array.js) the task will return a duplicate input error.

> gulp-google-closure-compiler: ERROR - Duplicate input: array/array.js

Both array.js files are here empty, and main.js only contains `goog.module('app');`

Worked until google-closure-compiler@20170409.0.0
Started breaking from google-closure-compiler@20170423.0.0.

Thanks!

**Comment by ChadKillingsworth** [comment]
You need to use the base parameter to specify where the globs should start from. Otherwise, gulp uses the first wildcard position.

```js
gulp.src(paths, {base: '.'})
```

Prior to the 20170423 version, there was a workaround in place for absolute paths that prevented this from being an issue.
