### ISSUE TITLE
create_source_maps option not generating sourceMaps files

### ISSUE THREAD

**Issue by mrudelle** [google/closure-compiler-npm#65]
Source maps files don't seem to be generated with the gulp module. Although when using the exact same set of params through command line, the sourceMaps files are correctly generated.

I use this dummy example:
```
gulp.task('dummy', function () {

    return closureCompiler({
        js: /* files */,
        externs: /* externs files */,
        compilation_level: googleClosure.COMPILE_ADVANCED,
        warning_level: 'VERBOSE',
        language_in: 'ECMASCRIPT6_STRICT',
        language_out: 'ECMASCRIPT5_STRICT',
        js_output_file: /* output filename */,
        create_source_map: 'path/out.js.map',
    })
        .src()
        .pipe(gulp.dest(/* output folder */));
});
```

**Comment by ChadKillingsworth** [comment]
When using gulp, the data is returned as a stream. That includes the sourcemap. It's expected that you'll use the gulp sourcemaps plugin. The `create_source_map` option is completely ignored with gulp. Source maps are always created and returned with the vinyl file.
