### ISSUE TITLE
Grunt plugin processes not all sources

### ISSUE THREAD

**Issue by dimalit** [google/closure-compiler-npm#66]
Hello!

I've been trying to minimize my sources with google-closure-compiler and Grunt.
After I set all up and execute grunt - I successfully get output file, but it seems to be "truncated". It looks like closure compiler processes 9 files in alphabetical order - and ignores the rest.

On the contrary, when I execute compiler.jar directly it successfully outputs all results.

Here I attached a sample "project". To use it do the following:
- "npm install" to get deps;
- "grunt"

It will rewrite "output" file test_framework.js. Look into this file afterwards - it will contain contents of files A.js through F.js - but it will lack G.js..K.js! (mysteriously - it only processed 6 files!)

npm 3.5.2
nodejs v4.2.6
google-closure-compiler@^20170521.0.0

Hope this is enough to identify the issue.
Thank you!

[gcc_bug.zip](https://github.com/google/closure-compiler-npm/files/1094876/gcc_bug.zip)

**Comment by ChadKillingsworth** [comment]
It looks like the compiler isn't waiting for the end of the input to begin processing. Unfortunately I don't have the bandwidth to tackle this right now.

**Comment by henrydawson** [comment]
I'm having this problem as well. Did anyone find a solution for this? I have a source list of about 140 files, and it seems to get about 100 of them, but not all.

I ended up concatinating the files in a separate task, and then passing the concatinated file to closure compiler. This works, but you lose sourceMaps.

**Comment by rusekr** [comment]
Using to compile 1-1 (without concatenate) for project with 200+ files and grunt config:

```
      node: {
        files: [
    'bin/**/*.js',
    
    'modules/*/**/*.js',
    '!modules/*/node_modules/**/*.js',

    'cron/**/*.js',
    'lib/**/*.js',
    'models/**/*.js',
    'api/**/*.js',
    'routes/**/*.js',
    'update/**/*.js',

    'controllers/**/main.js',
    'controllers/**/master.js',
    'controllers-modules/**/*.js'
  ],
            dest: '.builttemp',
            cwd: 'built'
          }
        ],
        options: {
          env: 'CUSTOM',
          compilation_level: 'SIMPLE',
          language_in: 'STABLE',
          language_out: 'ECMASCRIPT_2015',
          strict_mode_input: true
        }
      }
```
and it goes well. All files compiled

**Comment by concavelenz** [comment]
The grunt plugin is community maintained.  Proposed PRs welcome

**Comment by ChadKillingsworth** [comment]
Changes were made to Grunt in #229. Since we have no recent reports of this, I'm going to go ahead and close this issue.
