### ISSUE TITLE
Add method to override Compiler.prototype.javaPath

### ISSUE THREAD

**Issue by bansawbanchee** [google/closure-compiler-npm#68]
Would be nice to have a method to override Compiler.prototype.javaPath. I package up JRE in a dependency module. Java's path is platform specific depending on the OS you install the dependency on. By doing this I am able to utilize GCC without Java needing to be installed on the machine running GCC since it only needs JRE to do its thing.

As of today I am currently overriding the prototype before instantiating the compiler like so...

```
var Compiler = require('google-closure-compiler');

// not sure I like this... what if this changes?
Compiler.prototype.javaPath = '/node_modules/MODULE_NAME/jre/jre1.8.0_131.jre/Contents/Home/bin/java';

var compiler = new Compiler({args});
```

**Comment by ChadKillingsworth** [comment]
Changing the prototype was the intended solution. I really need to just document it. Why don't you like that?

**Comment by bansawbanchee** [comment]
Yea, that's what I ended up doing. Thanks.

**Comment by bansawbanchee** [comment]
apologies... I read it as "why don't you do that".

I wanted to be future safe in case you decide you don't like that property
name down the road and decide to change it.

At the end of the day documenting it would satisfy the request as I
wouldn't assume the possibility of a breaking change on something
documented.

**Comment by ChadKillingsworth** [comment]
This is now documented
