### ISSUE TITLE
create_source_map appears not to work

### ISSUE THREAD

**Issue by WillsB3** [google/closure-compiler-npm#78]
I'm not sure if this is a problem with the gulp integration, compiler itself or my own code :/

Steps to reproduce:

1. git clone git@github.com:WillsB3/closure-compiler-testing.git
2. Switch to the `sourcemaps` branch
3. `npm i`
4. `gulp build`
5. Observe that there is no `example.map` file generated anywhere in the project.

[Here](https://github.com/WillsB3/closure-compiler-testing/blob/sourcemaps/gulpfile.js#L30) is the config I'm passing to the compiler:

```js
.pipe(closureCompiler({
    compilation_level: 'SIMPLE',
    create_source_map: 'example.map',
    dependency_mode: 'STRICT',
    entry_point: path.join('.', 'src', 'js', 'main.js'),
    externs: [
        // path.join(paths.npm, 'closurecompiler-externs', 'core.js')
    ],
    warning_level: 'VERBOSE',
    language_in: 'ECMASCRIPT6_STRICT',
    language_out: 'ECMASCRIPT5_STRICT',
    output_wrapper: '(function(){\n%output%\n}).call(this)',
    js_output_file: 'output.min.js'
}))
```

Am I doing something wrong that prevents the sourcemap from being generated?

**Comment by ChadKillingsworth** [comment]
With gulp, you need to use the gulp-sourcemaps plugin: https://www.npmjs.com/package/gulp-sourcemaps

The compiler ignores create_source_map flag and the source map is always returned along with the source to gulp.

**Comment by WillsB3** [comment]
Thanks so much - that works. Would a PR adding this to the docs be helpful (unless it was there and I just didn't see it..)

**Comment by ChadKillingsworth** [comment]
It's there - but feel free to make it clearer: https://github.com/google/closure-compiler-npm#gulp-sourcemaps

**Comment by koto** [comment]
The info about the source map configuration is no longer present at https://github.com/google/closure-compiler-npm/tree/master/packages/google-closure-compiler README.

**Comment by koto** [comment]
OK, found it, sorry: https://github.com/google/closure-compiler-npm/blob/master/packages/google-closure-compiler/docs/gulp.md#gulp-sourcemaps
