### ISSUE TITLE
Closure Compiler "module" option, using gulp, does not properly split the output js as expected

### ISSUE THREAD

**Issue by rockywaugh** [google/closure-compiler-npm#79]
My apologies if this issue has already been covered, but it seems as though no matter how you change the number of module allocation per file, 

![image](https://user-images.githubusercontent.com/2791608/38381199-e4260b94-38ba-11e8-8716-b3ef3324a978.png)

I still get one js file with one line of code (usually a line that just states 'use strict') and the other file containing the rest of the compiled js output.  This defeats the purpose if the intention is to equally split the js file up due to environment file size restrictions.  I'm wondering if I'm doing something wrong or its just that no one else has these similar app.js file size restrictions. It's shocking that no one else has reported this same issue.

**Comment by ChadKillingsworth** [comment]
I think you main misunderstand how the module flag works. You cannot arbitrarily divide code into different files. The compiler will actually check that code in your app1 module does not depend on code in your app2 file. If any part of app1 references a symbol in app2, then the compiler will output it in the app1 module.

This isn't an issue with the npm wrapper, so I'm closing this. You may want to ask questions on StackOverflow on this.

**Comment by rockywaugh** [comment]
Hi @ChadKillingsworth .  I'm a little confused then as to the purpose of putting any module numeric value down if it does not have the ability to at least attempt to split the module allocation across files.  I've been told by colleagues that the python implementation of this compiler functionality does indeed allocate the compiled js across files.  Have you done a comparison of this feature?

**Comment by ChadKillingsworth** [comment]
The compiler does split code - I use that functionality regularly. However as I said, the module tree specified must make sense.

If any of the files in your `app1` module reference symbols in `app2`, the compiler will simply move the files up into `app1`.

**Comment by ChadKillingsworth** [comment]
I'm not sure what the "python" version is you refer to. The compiler is distributed as a Java jar, native images and a JS library.

There are some closure-library python scripts (closure-bundler) which scan files then invoke the compiler.

But in general, all versions of the compiler work identically. The JS version doesn't support all the flags though. But if it does support the flag, it works the same way as the production version.
