### ISSUE TITLE
Compiling module: variable module is undeclared, property never defined

### ISSUE THREAD

**Issue by Extarys** [google/closure-compiler-npm#82]
I'm trying to compile a npm module that run in the browser but I keep getting this error.
After modifying the script and removing everything related node modules and AMD, I get other errors:

```
var root = WINDOW ? window : {};
  if (root.JS_SHA3_NO_WINDOW) {
    WINDOW = false;
  }
```

> src/eng/lib-sha3.js:29: WARNING - Property JS_SHA3_NO_ARRAY_BUFFER never defined on root

the goal here is to create 1 single file from multiple files and the mian file require some libraries that I don't want to include in the global scope:
```
return gulp.src('./src/eng/**/*.js', {base: './'})
    pipe(sourcemaps.init())
    pipe(closureCompiler({
      compilation_level: 'SIMPLE',
      warning_level: 'VERBOSE',
      language_in: 'ECMASCRIPT6_STRICT',
      language_out: 'ECMASCRIPT5_STRICT',
      output_wrapper: '(function(){\n%output%\n}).call(this)',
      js_output_file: 'eng.min.js'
    }))
    pipe(gulp.dest('./public'))
```

Is there a way to tell the compiler to ignore errors in a specific file?
Is there any workaround or solution to this?
Thanks!

**Comment by ChadKillingsworth** [comment]
Use the `hide_warnings_for` option. It takes a path segment.

```js
hide_warnings_for: 'node_modules/problem_lib/foo.js'
``
