### ISSUE TITLE
Grunt task fails because of broken dependency

### ISSUE THREAD

**Issue by vsa** [google/closure-compiler-npm#92]
Starting with version 20180610, the Grunt task fails with the message "Error: Cannot find module 'gulp'". Commit 1b6dea1b1c changed the file [lib/grunt/index.js](https://github.com/google/closure-compiler-npm/commit/1b6dea1b1c1f294be8cb4db6cbc39153a3b72ce3#diff-52a91e4834106ff2d7554fdc73b9e56d) to require the "gulp" module directly, but it's only part of the "dev dependencies" of the package and won't be installed by default.

Is there a chance to get this corrected?

**Comment by ChadKillingsworth** [comment]
Yes - sure thing.

**Comment by vsa** [comment]
Thanks, much appreciated.

**Comment by Baiteman** [comment]
I'm facing the same problem, so I also would appreciate a change in this aspect greatly ;)

**Comment by ChadKillingsworth** [comment]
This was fixed by #93
