### ISSUE TITLE
npm package is fatter than before

### ISSUE THREAD

**Issue by leeoniya** [google/closure-compiler-npm#95]
hey @ChadKillingsworth,

i try to keep my `node_modules` weight as small as possible, and have noticed that `google-closure-compiler` is much heavier than the previous `google-closure-compiler-js`. i do see that it has facilities for detecting what version to run behind the scenes (native, java or js) and spends some time potentially downloading those. however, if i explicitly want the js version, then all i technically need is the compiler itself (`jscomp.js`) which is a mere 3.2MB single file. ideally, my build script would simply download & require this file (is it hosted anywhere?) without any additional npm dependency bloat.

below is a screenshot of `node_modules` stats with `google-closure-compiler-js` (left) and the current `google-closure-compiler` (right). if i just grabbed the single `jscomp.js` file myself, the result would be about 13MB smaller than even the former.

do you have any advice?

thanks!

![closure-compiler](https://user-images.githubusercontent.com/43234/42911687-a361ef3a-8ab1-11e8-83c3-7ca1b04d4a1a.png)

**Comment by leeoniya** [comment]
here's what it looks like if i copy `jscomp.js` plus the `closure-compiler-js.js` shim into a `./lib` folder and remove all `google-closure-compiler*` npm dependencies:

![closure-compiler-2](https://user-images.githubusercontent.com/43234/42913324-00540090-8aba-11e8-80d4-185ff27b02ae.png)

**Comment by ChadKillingsworth** [comment]
Unfortunately that is too much for us to maintain right now. It's also much harder for people to keep plugins in sync with compiler versions for this strategy.

We knew that combining repos would increase the size of the package, but this is after all a build tool and rarely used in production.

The benefits of being able to switch between platforms with an single option far outweigh the size constraints.

**Comment by leeoniya** [comment]
understood. is there anywhere that a pre-built `jscomp.js` can be fetched from?

if not, i'll just maintain https://github.com/domvm/closure-compiler-js-prebuilt manually.

**Comment by ChadKillingsworth** [comment]
Let me talk to the team about adding the prebuilt jscomp.js and native binaries to github release.

**Comment by leeoniya** [comment]
awesome, thank you.
